name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.app

    - name: Build and test
      run: xcodebuild clean build test -project CryptoCoin.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 18.4" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
