name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: macos-15-xlarge

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and test
      run: xcodebuild clean build test -project CryptoCoin.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=18.4,name=iPhone 16 Pro" ONLY_ACTIVE_ARCH=YES
